services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: baseTaller
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  db_init:
    image: postgres:latest
    depends_on:
      - db
    environment:
      PGPASSWORD: admin
    entrypoint:
      - sh
      - -c
      - |
        # Esperar a que Postgres acepte conexiones
        until pg_isready -h db -p 5432; do
          echo "Waiting for postgres..."
          sleep 1
        done

        # Crear tabla product de forma idempotente
        psql -h db -U admin -d baseTaller <<'EOSQL'
        CREATE TABLE IF NOT EXISTS product (
          id     SERIAL PRIMARY KEY,
          name   TEXT UNIQUE NOT NULL,
          stock  INTEGER NOT NULL,
          status VARCHAR(20) NOT NULL
        );

        -- Inserciones idempotentes: solo se crean si NO existen
        INSERT INTO product(name, stock, status)
        SELECT 'Producto 1',100,'available'
        WHERE NOT EXISTS (
          SELECT 1 FROM product WHERE name='Producto 1'
        );

        INSERT INTO product(name, stock, status)
        SELECT 'Producto 2',100,'available'
        WHERE NOT EXISTS (
          SELECT 1 FROM product WHERE name='Producto 2'
        );

        INSERT INTO product(name, stock, status)
        SELECT 'Producto 3',100,'available'
        WHERE NOT EXISTS (
          SELECT 1 FROM product WHERE name='Producto 3'
        );
        EOSQL
    restart: no


  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # para conexiones AMQP
      - "15672:15672"   # para la consola de administración web
    restart: always


  quarkus-app:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    image: order-service:latest
    ports:
      - "8080:8080"   # expone 8080 en localhost
    expose:
      - "8080"        # para la red interna de Docker
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/baseTaller
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
      QUARKUS_RABBITMQ_HOST: rabbitmq
      QUARKUS_RABBITMQ_PORT: "5672"
    depends_on:
      - db
      - rabbitmq

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    restart: always

volumes:
  pgdata:


