services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: baseTaller
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # para conexiones AMQP
      - "15672:15672"   # para la consola de administración web
    restart: always

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    restart: always

volumes:
  pgdata:


