# Número de réplicas (parámetro configurable)
replicaCount: 1

# Configuración de la imagen
image:
  repository: alexoberco/taller-quarkus-jvm
  tag: latest
  pullPolicy: IfNotPresent

# Puerto en el que la aplicación escucha
service:
  port: 8080

# Variables de entorno (puedes ampliar con la configuración de datasource, rabbitmq, etc.)
env:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://my-postgres-postgresql:5432/baseTaller"
  QUARKUS_DATASOURCE_USERNAME: "admin"
  QUARKUS_DATASOURCE_PASSWORD: "admin"
  QUARKUS_RABBITMQ_HOST: "my-rabbitmq"
  QUARKUS_RABBITMQ_PORT: "5672"

# Otras configuraciones opcionales (por ejemplo, labels personalizados)
labels: {}
