apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-init
  name: db-init
spec:
  containers:
    - command:
        - sh
        - -c
        - |
          # Esperar a que Postgres acepte conexiones
          until pg_isready -h db -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done

          # Inserciones idempotentes: solo se crean si NO existen
          psql -h db -U admin -d baseTaller -c "INSERT INTO product(name, stock, status) SELECT 'Producto 1',100,'available' WHERE NOT EXISTS (SELECT 1 FROM product WHERE name='Producto 1');"
          psql -h db -U admin -d baseTaller -c "INSERT INTO product(name, stock, status) SELECT 'Producto 2',100,'available' WHERE NOT EXISTS (SELECT 1 FROM product WHERE name='Producto 2');"
          psql -h db -U admin -d baseTaller -c "INSERT INTO product(name, stock, status) SELECT 'Producto 3',100,'available' WHERE NOT EXISTS (SELECT 1 FROM product WHERE name='Producto 3');"
      env:
        - name: PGPASSWORD
          value: admin
      image: postgres:latest
      name: db-init
  restartPolicy: Never
