primary:
  initdb:
    scripts:
      init-products.sql: |
        -- Crear la tabla "product" si no existe.
        CREATE TABLE IF NOT EXISTS product (
           id SERIAL PRIMARY KEY,
           name VARCHAR(255) NOT NULL,
           stock INTEGER NOT NULL,
           status VARCHAR(50)
        );
        
        -- Insertar productos si no existen.
        INSERT INTO product(name, stock, status)
        SELECT 'Producto 1', 100, 'available'
        WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Producto 1');
        
        INSERT INTO product(name, stock, status)
        SELECT 'Producto 2', 100, 'available'
        WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Producto 2');
        
        INSERT INTO product(name, stock, status)
        SELECT 'Producto 3', 100, 'available'
        WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Producto 3');
