apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  namespace: postgress
  labels:
    app: quarkus-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: quarkus-app
